Session and static
fugazi-io/connector.node pull request #7
Opened 2017-08-01 15:47 UTC by amir-arad

add options for session and static serving of entire folders

2017-08-05 23:37 UTC, nitzantomer requested changes

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/middleware/session.ts
> +	// /**
all of the commented out code and comments are needed?
it looks like it's copied from somewhere, maybe just add the url as a comment above?

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +import serve = require('koa-static');
(formatting)
double quotes: `require("koa-static")`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +import {Config as SessionConfig, middleware as session, Session} from "./middleware/session";
(formatting)
pad it with spaces:
`{ Config as SessionConfig, middleware as session, Session }`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +	session: Session|undefined;
(formatting)
add spaces:
`session: Session | undefined;`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +	private _session: Partial<SessionConfig>|undefined;
(formatting)
add spaces:
`private _session: Partial<SessionConfig> | undefined;`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +	session(config:Partial<SessionConfig> = {}){
(formatting)
add spaces:
`session(config: Partial<SessionConfig> = {}) {`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +				folders:Array<string>,
(formatting)
add space:
`folders: Array<string>,`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +				sessionConfig: Partial<SessionConfig>|undefined,
(formatting)
add spaces:
`sessionConfig: Partial<SessionConfig> | undefined,`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +		if(sessionConfig !== undefined) {
(formatting)
add space:
`if (sessionConfig !== undefined) {`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +			if(sessionConfig.keygrip) {
(formatting)
add space:
`if (sessionConfig.keygrip) {`

2017-08-05 23:37 UTC, nitzantomer commented on scripts/src/server.ts
> +			folders.forEach((folder)=>{
(formatting)
add spaces, also no need to wrap one param in brackets:
`folders.forEach(folder => {`

2017-08-10 06:11 UTC, amir-arad commented on scripts/src/server.ts
> +			folders.forEach((folder)=>{
unsure where to add spaces

2017-08-10 06:12 UTC, amir-arad commented on scripts/src/server.ts
> +			folders.forEach((folder)=>{
unsure where to add spaces

2017-08-12 17:07 UTC, merged